import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
// import { signIn, signOut, useSession } from "next-auth/react";

// import { api } from "../utils/api";
import Friend from "../components/Friend";
import { useState } from "react";

const EventCreator = (
  icon: string,
  eventName: string,
  timeRange: string,
  days: string
) => {
  return {icon, eventName, timeRange, days}
}

const Schedule: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  // const [events, setEvents] = useState([
  //   EventCreator("📲", "CIS 4515", "9:30 am - 10:50 am", "Monday, Tuesday, Wednesday"),
  //   EventCreator("📚", "IH 0852", "11:00 am - 12:20 am", "Tuesday, Thursday"),
  //   EventCreator("⚡", "PHYS 1061", "9:20 am - 10:30 am", "Tuesday, Thursday"),
  //   EventCreator("📊", "CIS 2033", "12:00 pm - 12:50 pm", "Monday, Wednesday, Friday"),
  //   EventCreator("🎉", "CIS 3603", "5:30 pm - 8:00 pm", "Monday"),
  //   EventCreator("🛠️", "Work", "6:30 pm - 9:50 pm", "Tuesday, Thursday, Friday"),
  //   EventCreator("🛠️", "Work", "6:30 pm - 9:50 pm", "Tuesday, Thursday, Friday"),
  //   EventCreator("🛠️", "Work", "6:30 pm - 9:50 pm", "Tuesday, Thursday, Friday"),
  //   EventCreator("🛠️", "Work", "6:30 pm - 9:50 pm", "Tuesday, Thursday, Friday"),
  //   EventCreator("🛠️", "Work", "6:30 pm - 9:50 pm", "Tuesday, Thursday, Friday"),
  //   EventCreator("🛠️", "Work", "6:30 pm - 9:50 pm", "Tuesday, Thursday, Friday"),
  // ]);

  return (
    <>
      <Head>
        <title>Schedule Sync</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full w-full flex-col items-center justify-start bg-white gap-2 overflow-hidden">
        <div className="flex h-full w-full flex-col items-center justify-start relative overflow-scroll">
          {/* {events.map((event) => {
            return <Friend key={event.eventName} {...event}></Friend>
          })} */}
          <Friend name={"Jacob Snarr"} busy={false} ></Friend>
        </div>
      </main>
    </>
  );
};

export default Schedule;