import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
// import { signIn, signOut, useSession } from "next-auth/react";

// import { api } from "../utils/api";
import Friend from "../components/Friend";

const Schedule: NextPage = () => {

  return (
    <>
      <Head>
        <title>Schedule Sync</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full w-full flex-col items-center justify-start bg-white gap-2 overflow-hidden">
        <div className="flex h-full w-full flex-col items-center justify-start relative overflow-scroll">
          {/* {events.map((event) => {
            return <Friend key={event.eventName} {...event}></Friend>
          })} */}
          <Friend name={"Jacob Snarr"} busy={false} ></Friend>
        </div>
      </main>
    </>
  );
};

export default Schedule;